[package]
name = "sum_two_values"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.17.0"
clap = "4.0"
regex = "1.11.1"
rpassword = "5.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"
